# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
        
      - name: Restore NuGet packages
        run: nuget restore "BSA Browser.sln"
        
      - name: Build the Solution
        run: msbuild "BSA Browser.sln" /p:Configuration=Release
        
      - uses: benjlevesque/short-sha@v1.2
        id: short-sha
        with:
          length: 7
        
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body: "Automated build. Unstable"
          files: "BSA Browser\\bin\\Release\\BSA Browser.exe"
          prerelease: True
          tag_name: ${{ steps.short-sha.outputs.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
